# Generated by Django 4.2 on 2023-04-28 20:19

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Affiliate', null=True, verbose_name='affiliate_text')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='last_update')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=200, null=True)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faq',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='price', null=True, verbose_name='price_text')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='last_update')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='PrivacyTermsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PrivacyTermsAbout',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivacyTermsAboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('privacy_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True, verbose_name='privacy_text')),
                ('terms_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='terms text', null=True, verbose_name='terms_text')),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='About text', null=True, verbose_name='About_text')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='status')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='update_at')),
                ('last_update', models.DateTimeField(auto_now_add=True, verbose_name='last_update')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.privacytermsabout')),
            ],
            options={
                'verbose_name': 'privacy terms about Translation',
                'db_table': 'core_privacytermsabout_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
