# Generated by Django 4.2 on 2023-04-23 20:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Affiliate', null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='faq', null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faq',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='price', null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='PrivacyTermsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('Terms_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('About_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy',
            },
        ),
    ]
