# Generated by Django 4.2 on 2023-04-13 08:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='privacy_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True),
        ),
    ]
