# Generated by Django 4.2 on 2023-04-23 20:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=5)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='last_update',
            new_name='create_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='faq_text',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='name',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='ordernumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PrivacyTermsAboutLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[], max_length=6)),
                ('privacy_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('Terms_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('About_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Privacy Policy Notice', null=True)),
                ('name', models.CharField(max_length=100)),
                ('privacy_terms_about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.privacytermsabout')),
            ],
            options={
                'verbose_name_plural': 'PrivacyTermsAbout',
            },
        ),
        migrations.CreateModel(
            name='PriceLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[], max_length=6)),
                ('price_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='price', null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.price')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='AffiliateLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[], max_length=6)),
                ('affiliate_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Affiliate', null=True)),
                ('name', models.CharField(max_length=100)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affiliate')),
            ],
        ),
    ]
