# Generated by Django 4.2 on 2023-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='last_update',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='last_update',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='privacytermsabout',
            old_name='last_update',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='affiliatelang',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliatelang',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='price',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricelang',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelang',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privacytermsabout',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privacytermsaboutlang',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacytermsaboutlang',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
