# Generated by Django 4.2 on 2023-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_privacy_privacy_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'Privacies'},
        ),
        migrations.AlterField(
            model_name='privacy',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
