# Generated by Django 4.2 on 2023-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_privacy_options_alter_privacy_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacy',
            name='name',
            field=models.CharField(default='PRIVACY', max_length=100),
            preserve_default=False,
        ),
    ]
