# Generated by Django 4.2 on 2023-04-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Faq'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name_plural': 'Privacies'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
    ]
