# Generated by Django 4.2 on 2023-05-15 15:16

import ckeditor_uploader.fields
import content.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Buttons',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100)),
                ('name_of_product_en', models.CharField(max_length=100, null=True)),
                ('name_of_product_fr', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_en', models.SlugField(null=True, unique=True)),
                ('slug_fr', models.SlugField(null=True, unique=True)),
                ('shopify_links', models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True)),
                ('shopify_price', models.DecimalField(decimal_places=2, help_text='Product price from shopify', max_digits=10)),
                ('product_thumbnail', models.ImageField(default='products/defaut_image_store_light_blue_bag.jpg', upload_to='thumbnails/')),
                ('store_logo', models.ImageField(blank=True, default='products/defaut_image_store.png', upload_to='image_store/')),
                ('aliexpress_order', models.IntegerField(default=0, help_text='Amount of aliexpress order generated')),
                ('aliexpress_price', models.DecimalField(decimal_places=2, help_text='Product price from aliexpress', max_digits=10)),
                ('likes', models.IntegerField(default=0, help_text='Amount of likes generated')),
                ('comment', models.IntegerField(default=0, help_text='Amount of comment generated')),
                ('views', models.IntegerField(default=0, help_text='Amount of views generated')),
                ('links_to_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A link that will take to ads', null=True)),
                ('links_to_others_stores', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A link that will take to the store', null=True)),
                ('links_to_others_suppliers', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('number_of_store_selling', models.IntegerField(default=0, help_text='Amount of store selling the product')),
                ('number_of_suppliers_selling', models.IntegerField(default=0, help_text='Amount of suppliers selling the product')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('is_faceBook', models.BooleanField(default=False)),
                ('is_pinterest', models.BooleanField(default=False)),
                ('is_tiktok', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('price_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Profit you get from this product', max_digits=10)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('aliexpress_total_sale', models.DecimalField(blank=True, decimal_places=2, help_text='Amount of aliexpress sale generated', max_digits=10)),
                ('buttons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buttons', to='content.button')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('countries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('call_to_action', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='content.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_sale', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.DateField(blank=True, default=django.utils.timezone.now, help_text='time, date, mois, june 30, dec 30...', null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OtherShopifyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('links', models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True)),
                ('country', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Other Shopify Links',
            },
        ),
        migrations.CreateModel(
            name='OtherAliexpressSuppliersLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('links', models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True)),
                ('country', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Other Aliexpress Suppliers Links',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', content.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.order')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='content.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_of_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_name', to='content.store'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technologies', to='content.technology'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_fr', models.CharField(max_length=30, null=True)),
                ('population', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.course')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
