# Generated by Django 4.1.6 on 2023-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='share',
        ),
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0, help_text='Amount of views generated'),
        ),
    ]
