# Generated by Django 4.2 on 2023-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheraliexpresssupplierslinks',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product price from aliexpress suppliers', max_digits=10, null=True),
        ),
    ]
