# Generated by Django 4.2 on 2023-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_otheraliexpresssupplierslinks_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='links_to_ads',
        ),
        migrations.RemoveField(
            model_name='course',
            name='links_to_others_stores',
        ),
        migrations.RemoveField(
            model_name='course',
            name='links_to_others_suppliers',
        ),
    ]
