# Generated by Django 4.1.6 on 2023-03-26 07:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_course_share_course_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='store_domaine_url',
            new_name='shopify_url',
        ),
        migrations.AddField(
            model_name='course',
            name='product_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
