# Generated by Django 4.2 on 2023-05-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_course_links_to_ads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='facebook_angry',
            field=models.IntegerField(default=0, help_text='Amount of facebook angry'),
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_haha',
            field=models.IntegerField(default=0, help_text='Amount of facebook haha'),
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_like',
            field=models.IntegerField(default=0, help_text='Amount of facebook like'),
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_love',
            field=models.IntegerField(default=0, help_text='Amount of facebook love'),
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_sad',
            field=models.IntegerField(default=0, help_text='Amount of facebook sad'),
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_wow',
            field=models.IntegerField(default=0, help_text='Amount of facebook wow'),
        ),
    ]
