# Generated by Django 4.2 on 2023-05-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_course_facebook_angry_course_facebook_haha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='comment',
            new_name='facebook_comment',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='views',
            new_name='facebook_views',
        ),
        migrations.RemoveField(
            model_name='course',
            name='likes',
        ),
        migrations.AddField(
            model_name='course',
            name='facebook_shares',
            field=models.IntegerField(default=0, help_text='Amount of facebook_shares generated'),
        ),
    ]
