# Generated by Django 4.1.6 on 2023-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_is_instagram_course_is_pinterest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Store name',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='shopify_url',
        ),
    ]
