# Generated by Django 4.1.6 on 2023-03-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_store_remove_course_shopify_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='product_video',
        ),
    ]
