# Generated by Django 4.1.6 on 2023-03-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_course_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='store_names',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_store', to='content.store'),
        ),
    ]
