# Generated by Django 4.1.6 on 2023-03-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_course_store_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='store_names',
        ),
    ]
