# Generated by Django 4.1.6 on 2023-03-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_course_store_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Price'},
        ),
    ]
