# Generated by Django 4.1.6 on 2023-03-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_category_alter_store_options_alter_store_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'Stores'},
        ),
        migrations.AlterField(
            model_name='course',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='content.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
