# Generated by Django 4.1.6 on 2023-03-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_store_options_alter_course_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='primary_category',
        ),
        migrations.AddField(
            model_name='course',
            name='name_of_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_name', to='content.store'),
        ),
    ]
