# Generated by Django 4.1.6 on 2023-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_store_options_remove_course_primary_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='name_of_product',
        ),
    ]
