# Generated by Django 4.1.6 on 2023-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_rename_image_store_course_store_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='store_thumbnail',
            new_name='product_thumbnail',
        ),
    ]
