# Generated by Django 4.1.6 on 2023-03-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_rename_store_thumbnail_course_product_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='ads_run_since',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='last_seen',
            new_name='date_we_found',
        ),
        migrations.RemoveField(
            model_name='course',
            name='product_vimeo_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='store_name',
        ),
    ]
