# Generated by Django 4.1.6 on 2023-03-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_rename_created_at_course_ads_run_since_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='links_to_a_single_store',
            new_name='shopify_links',
        ),
    ]
