# Generated by Django 4.1.6 on 2023-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_rename_links_to_a_single_store_course_shopify_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='has_video',
            field=models.BooleanField(default=True),
        ),
    ]
