# Generated by Django 4.1.6 on 2023-03-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='course',
        ),
    ]
