# Generated by Django 4.1.6 on 2023-04-02 06:23

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_rename_product_orderitem_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='links_to_others_stores',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A link that will take to the store', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='course',
            name='links_to_others_suppliers',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='course',
            name='text_that_comes_with_ads',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='call_to_action',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
