# Generated by Django 4.1.6 on 2023-04-02 07:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_course_links_to_others_stores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='links_to_others_stores',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A link that will take to the store', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='links_to_others_suppliers',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='text_that_comes_with_ads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='call_to_action',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
