# Generated by Django 4.1.6 on 2023-04-02 08:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_course_links_to_others_stores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='links_to_ads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A link that will take to ads', null=True),
        ),
    ]
