# Generated by Django 4.1.6 on 2023-04-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_category_course_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='content.category'),
        ),
    ]
