# Generated by Django 4.1.6 on 2023-04-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_button_language_remove_course_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='languages',
        ),
    ]
