# Generated by Django 4.1.6 on 2023-04-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_alter_button_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_photo',
        ),
        migrations.AlterField(
            model_name='course',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_faceBook',
            field=models.BooleanField(default=False),
        ),
    ]
