# Generated by Django 4.1.6 on 2023-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_remove_course_has_photo_alter_course_has_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
    ]
