# Generated by Django 4.2 on 2023-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_course_has_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='aliexpress_price',
            field=models.DecimalField(decimal_places=2, help_text='Product price from aliexpress', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='aliexpress_total_sale',
            field=models.DecimalField(decimal_places=2, help_text='Amount of aliexpress sale generated', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_margin',
            field=models.DecimalField(decimal_places=2, default=20000.0, help_text='Profit you get from this product', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='shopify_price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Product price from shopify', max_digits=10),
            preserve_default=False,
        ),
    ]
